server:
  port: 20092

spring:
  webflux:
    base-path: /kpl
  application:
    name: account-service
#  data:
#    mongodb:
#      name: ${KPL_USER_DB_NAME:kpl-users}
#      uri: ${SPRING_DATA_MONGO_URI:mongodb://localhost:27017/${spring.data.mongodb.name}?retryWrites=true&w=majority}